#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -fomit-frame-pointer -Wextra -Wall -std=c++11 -fexceptions -Wno-unused-parameter
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = -O1 -s

INC_BIN = $(INC) -Isrc
CFLAGS_BIN = $(CFLAGS)
RESINC_BIN = $(RESINC)
RCFLAGS_BIN = $(RCFLAGS)
LIBDIR_BIN = $(LIBDIR)
LIB_BIN = $(LIB)
LDFLAGS_BIN = $(LDFLAGS)
OBJDIR_BIN = obj
DEP_BIN = 
OUT_BIN = bin/higueulc

OBJ_BIN = $(OBJDIR_BIN)/src/Eagle_bin_65816.o $(OBJDIR_BIN)/src/rmake.o $(OBJDIR_BIN)/src/main.o $(OBJDIR_BIN)/src/constant_folding.o $(OBJDIR_BIN)/src/Eagle_parser.o $(OBJDIR_BIN)/src/Eagle_convert_asm.o $(OBJDIR_BIN)/src/Eagle_bin_z80.o $(OBJDIR_BIN)/src/Eagle_bin_AltairX.o $(OBJDIR_BIN)/src/Eagle_bin_80286.o $(OBJDIR_BIN)/src/Eagle.o $(OBJDIR_BIN)/src/Eagle_bin_6502.o $(OBJDIR_BIN)/src/Eagle_asm_z80.o $(OBJDIR_BIN)/src/Eagle_asm_AltairX.o $(OBJDIR_BIN)/src/Eagle_asm_80286.o $(OBJDIR_BIN)/src/Eagle_asm_65816.o $(OBJDIR_BIN)/src/Eagle_asm_6502.o $(OBJDIR_BIN)/src/Eagle_asm.o

all: bin

clean: clean_bin

before_bin: 
	test -d bin || mkdir -p bin
	test -d $(OBJDIR_BIN)/src || mkdir -p $(OBJDIR_BIN)/src

after_bin: 

bin: before_bin out_bin after_bin

out_bin: before_bin $(OBJ_BIN) $(DEP_BIN)
	$(LD) $(LIBDIR_BIN) -o $(OUT_BIN) $(OBJ_BIN)  $(LDFLAGS_BIN) $(LIB_BIN)

$(OBJDIR_BIN)/src/Eagle_bin_65816.o: src/Eagle_bin_65816.cpp
	$(CXX) $(CFLAGS_BIN) $(INC_BIN) -c src/Eagle_bin_65816.cpp -o $(OBJDIR_BIN)/src/Eagle_bin_65816.o

$(OBJDIR_BIN)/src/rmake.o: src/rmake.cpp
	$(CXX) $(CFLAGS_BIN) $(INC_BIN) -c src/rmake.cpp -o $(OBJDIR_BIN)/src/rmake.o

$(OBJDIR_BIN)/src/main.o: src/main.cpp
	$(CXX) $(CFLAGS_BIN) $(INC_BIN) -c src/main.cpp -o $(OBJDIR_BIN)/src/main.o

$(OBJDIR_BIN)/src/constant_folding.o: src/constant_folding.cpp
	$(CXX) $(CFLAGS_BIN) $(INC_BIN) -c src/constant_folding.cpp -o $(OBJDIR_BIN)/src/constant_folding.o

$(OBJDIR_BIN)/src/Eagle_parser.o: src/Eagle_parser.cpp
	$(CXX) $(CFLAGS_BIN) $(INC_BIN) -c src/Eagle_parser.cpp -o $(OBJDIR_BIN)/src/Eagle_parser.o

$(OBJDIR_BIN)/src/Eagle_convert_asm.o: src/Eagle_convert_asm.cpp
	$(CXX) $(CFLAGS_BIN) $(INC_BIN) -c src/Eagle_convert_asm.cpp -o $(OBJDIR_BIN)/src/Eagle_convert_asm.o

$(OBJDIR_BIN)/src/Eagle_bin_z80.o: src/Eagle_bin_z80.cpp
	$(CXX) $(CFLAGS_BIN) $(INC_BIN) -c src/Eagle_bin_z80.cpp -o $(OBJDIR_BIN)/src/Eagle_bin_z80.o

$(OBJDIR_BIN)/src/Eagle_bin_AltairX.o: src/Eagle_bin_AltairX.cpp
	$(CXX) $(CFLAGS_BIN) $(INC_BIN) -c src/Eagle_bin_AltairX.cpp -o $(OBJDIR_BIN)/src/Eagle_bin_AltairX.o

$(OBJDIR_BIN)/src/Eagle_bin_80286.o: src/Eagle_bin_80286.cpp
	$(CXX) $(CFLAGS_BIN) $(INC_BIN) -c src/Eagle_bin_80286.cpp -o $(OBJDIR_BIN)/src/Eagle_bin_80286.o

$(OBJDIR_BIN)/src/Eagle.o: src/Eagle.cpp
	$(CXX) $(CFLAGS_BIN) $(INC_BIN) -c src/Eagle.cpp -o $(OBJDIR_BIN)/src/Eagle.o

$(OBJDIR_BIN)/src/Eagle_bin_6502.o: src/Eagle_bin_6502.cpp
	$(CXX) $(CFLAGS_BIN) $(INC_BIN) -c src/Eagle_bin_6502.cpp -o $(OBJDIR_BIN)/src/Eagle_bin_6502.o

$(OBJDIR_BIN)/src/Eagle_asm_z80.o: src/Eagle_asm_z80.cpp
	$(CXX) $(CFLAGS_BIN) $(INC_BIN) -c src/Eagle_asm_z80.cpp -o $(OBJDIR_BIN)/src/Eagle_asm_z80.o

$(OBJDIR_BIN)/src/Eagle_asm_AltairX.o: src/Eagle_asm_AltairX.cpp
	$(CXX) $(CFLAGS_BIN) $(INC_BIN) -c src/Eagle_asm_AltairX.cpp -o $(OBJDIR_BIN)/src/Eagle_asm_AltairX.o

$(OBJDIR_BIN)/src/Eagle_asm_80286.o: src/Eagle_asm_80286.cpp
	$(CXX) $(CFLAGS_BIN) $(INC_BIN) -c src/Eagle_asm_80286.cpp -o $(OBJDIR_BIN)/src/Eagle_asm_80286.o

$(OBJDIR_BIN)/src/Eagle_asm_65816.o: src/Eagle_asm_65816.cpp
	$(CXX) $(CFLAGS_BIN) $(INC_BIN) -c src/Eagle_asm_65816.cpp -o $(OBJDIR_BIN)/src/Eagle_asm_65816.o

$(OBJDIR_BIN)/src/Eagle_asm_6502.o: src/Eagle_asm_6502.cpp
	$(CXX) $(CFLAGS_BIN) $(INC_BIN) -c src/Eagle_asm_6502.cpp -o $(OBJDIR_BIN)/src/Eagle_asm_6502.o

$(OBJDIR_BIN)/src/Eagle_asm.o: src/Eagle_asm.cpp
	$(CXX) $(CFLAGS_BIN) $(INC_BIN) -c src/Eagle_asm.cpp -o $(OBJDIR_BIN)/src/Eagle_asm.o

clean_bin: 
	rm -f $(OBJ_BIN) $(OUT_BIN)
	rm -rf bin
	rm -rf $(OBJDIR_BIN)/src

.PHONY: before_bin after_bin clean_bin

